#:schema node_modules/wrangler/config-schema.json
name = "paperknife-db"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "paperknife-db"
database_id = "f8c23187-d464-4552-b059-f32f2bd8a23f"
