import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from "react";
import { notFound, redirect } from "next/navigation";
import Script from "next/script";
import { cn } from "@/lib/utils";
import CTA from "@/components/cta";
import ReportAbuse from "@/components/report-abuse";
import { getSiteData } from "@/lib/fetchers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          inter.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}


